/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["oauthAuthorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["oauthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMe"];
        trace?: never;
    };
    "/users/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPreferences"];
        put: operations["putPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSkills"];
        put: operations["putSkills"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotificationSettings"];
        put: operations["putNotificationSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listResumes"];
        put?: never;
        post: operations["uploadResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resumes/{resumeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resumeId: components["parameters"]["resumeId"];
            };
            cookie?: never;
        };
        get: operations["getResume"];
        put?: never;
        post?: never;
        delete: operations["deleteResume"];
        options?: never;
        head?: never;
        patch: operations["updateResume"];
        trace?: never;
    };
    "/resumes/{resumeId}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["setDefaultResume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resumes/{resumeId}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["analyzeResume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resumes/{resumeId}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadResume"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description CSV export of matched jobs for manual application (always available for SEARCH_LINK sources). */
        get: operations["exportJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSearchRuns"];
        put?: never;
        /** @description On-demand ingestion using my saved preferences (async). */
        post: operations["triggerSearchRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search-runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSearchRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMatch"];
        put?: never;
        post: operations["recomputeMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApplications"];
        put?: never;
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["applicationId"];
            };
            cookie?: never;
        };
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete: operations["deleteApplication"];
        options?: never;
        head?: never;
        patch: operations["updateApplication"];
        trace?: never;
    };
    "/applications/{applicationId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changeApplicationStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApplicationEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addApplicationContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Trigger automated application. Only succeeds when the job's connector compliance mode permits automation AND the user has opted in for that site; otherwise 409 with the manual-apply link. */
        post: operations["autoApply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDocuments"];
        put?: never;
        /** @description Generate a tailored resume / cover letter / recruiter email / LinkedIn message / cold email for a job. */
        post: operations["generateDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{documentId}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConversations"];
        put?: never;
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/conversations/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        get: operations["getConversation"];
        put?: never;
        post?: never;
        delete: operations["deleteConversation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/conversations/{conversationId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send a user message. Response is Server-Sent Events streaming assistant tokens, tool-call notices, and a final message object. */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Composite payload for the dashboard page (cached, refreshed nightly + on demand). */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ai/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAiSettings"];
        put: operations["putAiSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPrompts"];
        put?: never;
        post: operations["createPromptVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/prompts/{promptId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activatePrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listConnectors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/connectors/{connectorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateConnector"];
        trace?: never;
    };
    "/admin/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listWatchlist"];
        put?: never;
        post: operations["addWatchlistEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSchedules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/schedules/{taskKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSchedule"];
        trace?: never;
    };
    "/admin/schedules/{taskKey}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runScheduleNow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** @description Access token TTL seconds */
            expires_in?: number;
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id?: string;
            /** Format: email */
            email?: string;
            full_name?: string;
            /** @enum {string} */
            role?: "USER" | "ADMIN";
            timezone?: string;
            /** Format: date-time */
            created_at?: string;
        };
        /** @enum {string} */
        EmploymentType: "FULL_TIME" | "PART_TIME" | "CONTRACT" | "INTERNSHIP" | "TEMPORARY" | "UNKNOWN";
        /** @enum {string} */
        ContractArrangement: "W2" | "C1099" | "C2C" | "UNSPECIFIED";
        /** @enum {string} */
        WorkplaceType: "REMOTE" | "HYBRID" | "ONSITE" | "UNKNOWN";
        /** @enum {string} */
        SponsorshipFlag: "SPONSOR_FRIENDLY" | "NO_SPONSOR" | "UNKNOWN";
        /** @enum {string} */
        SeniorityLevel: "ENTRY" | "MID" | "SENIOR" | "LEAD" | "PRINCIPAL" | "UNKNOWN";
        /** @enum {string} */
        ApplicationStatus: "SAVED" | "INTERESTED" | "RESUME_GENERATED" | "APPLIED" | "RECRUITER_CONTACTED" | "OA_RECEIVED" | "INTERVIEW_SCHEDULED" | "REJECTED" | "OFFER" | "ACCEPTED" | "DECLINED";
        /** @enum {string} */
        DocumentType: "TAILORED_RESUME" | "COVER_LETTER" | "RECRUITER_EMAIL" | "LINKEDIN_MESSAGE" | "COLD_EMAIL";
        Preferences: {
            desired_titles?: string[];
            employment_types?: components["schemas"]["EmploymentType"][];
            contract_arrangements?: components["schemas"]["ContractArrangement"][];
            workplace_types?: components["schemas"]["WorkplaceType"][];
            locations?: {
                city?: string;
                state?: string;
                country?: string;
                radius_mi?: number;
            }[];
            countries?: string[];
            seniority?: components["schemas"]["SeniorityLevel"];
            years_experience?: number;
            visa_status?: string;
            work_authorization?: string;
            needs_sponsorship?: boolean;
            open_to_staffing?: boolean;
            salary_min?: number;
            salary_max?: number;
            salary_currency?: string;
            /** Format: date */
            availability_date?: string;
            notice_period_days?: number;
            auto_apply_enabled?: boolean;
            auto_apply_min_score?: number;
            auto_apply_daily_cap?: number;
        };
        UserSkill: {
            name: string;
            category?: string;
            years?: number;
            proficiency?: number;
        };
        NotificationSettings: {
            email_enabled?: boolean;
            daily_report_hour?: number;
            /** @description Write-only; returned masked */
            slack_webhook?: string;
            /** @description Write-only; returned masked */
            discord_webhook?: string;
        };
        Resume: {
            /** Format: uuid */
            id?: string;
            name?: string;
            is_default?: boolean;
            mime_type?: string;
            /** @description Parsed sections/experience/skills */
            structured?: Record<string, never>;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ResumeAnalysis: {
            ats_score?: number;
            strengths?: string[];
            gaps?: string[];
            suggestions?: string[];
            keyword_coverage?: {
                [key: string]: boolean;
            };
        };
        Company: {
            /** Format: uuid */
            id?: string;
            name?: string;
            website?: string;
            is_staffing_firm?: boolean;
            ats_type?: string;
        };
        Job: {
            /** Format: uuid */
            id?: string;
            title?: string;
            company?: components["schemas"]["Company"];
            connector_id?: string;
            url?: string;
            location_text?: string;
            workplace?: components["schemas"]["WorkplaceType"];
            employment?: components["schemas"]["EmploymentType"];
            arrangement?: components["schemas"]["ContractArrangement"];
            salary_min?: number;
            salary_max?: number;
            salary_currency?: string;
            /** Format: date-time */
            posted_at?: string;
            /** @description Convenience copy of overall match score */
            my_score?: number;
            sponsorship?: components["schemas"]["SponsorshipFlag"];
        };
        JobDetail: components["schemas"]["Job"] & {
            description_md?: string;
            extraction?: components["schemas"]["JobExtraction"];
            match?: components["schemas"]["MatchScore"];
            /**
             * Format: uuid
             * @description Present if already tracked
             */
            application_id?: string;
        };
        JobExtraction: {
            skills?: string[];
            tech_stack?: string[];
            responsibilities?: string[];
            benefits?: string[];
            sponsorship?: components["schemas"]["SponsorshipFlag"];
            seniority?: components["schemas"]["SeniorityLevel"];
            recruiter_name?: string;
            recruiter_contact?: string;
            /** @enum {string} */
            method?: "LLM" | "HEURISTIC" | "MIXED";
        };
        MatchScore: {
            /** Format: uuid */
            job_id?: string;
            /** Format: uuid */
            resume_id?: string;
            overall?: number;
            ats_pct?: number;
            resume_pct?: number;
            salary_score?: number;
            location_score?: number;
            visa_score?: number;
            skill_gap?: {
                skill?: string;
                required?: boolean;
                have?: boolean;
            }[];
            reasoning?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Match: {
            job?: components["schemas"]["Job"];
            score?: components["schemas"]["MatchScore"];
        };
        Application: {
            /** Format: uuid */
            id?: string;
            job?: components["schemas"]["Job"];
            status?: components["schemas"]["ApplicationStatus"];
            /** @enum {string} */
            method?: "MANUAL" | "API" | "AUTOMATED_FORM" | "EMAIL" | "REFERRAL";
            /** Format: date-time */
            applied_at?: string;
            /** Format: date-time */
            deadline_at?: string;
            /** Format: date-time */
            next_action_at?: string;
            salary_offered?: number;
            notes?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ApplicationDetail: components["schemas"]["Application"] & {
            events?: components["schemas"]["ApplicationEvent"][];
            contacts?: components["schemas"]["ApplicationContact"][];
            documents?: components["schemas"]["GeneratedDocument"][];
        };
        ApplicationEvent: {
            from_status?: components["schemas"]["ApplicationStatus"];
            to_status?: components["schemas"]["ApplicationStatus"];
            /** @enum {string} */
            actor?: "USER" | "SYSTEM" | "ASSISTANT";
            note?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ApplicationContact: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            recruiter_id?: string;
            role?: string;
            email?: string;
            notes?: string;
        };
        GeneratedDocument: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            job_id?: string;
            /** Format: uuid */
            application_id?: string;
            doc_type?: components["schemas"]["DocumentType"];
            /** @enum {string} */
            status?: "PENDING" | "READY" | "FAILED";
            content_md?: string;
            has_file?: boolean;
            model?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Conversation: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ConversationDetail: components["schemas"]["Conversation"] & {
            messages?: components["schemas"]["Message"][];
        };
        Message: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            role?: "USER" | "ASSISTANT" | "SYSTEM" | "TOOL";
            content?: string;
            tool_calls?: Record<string, never>[];
            /** Format: date-time */
            created_at?: string;
        };
        SearchRun: {
            id?: string;
            /** @enum {string} */
            status?: "RUNNING" | "SUCCESS" | "FAILED" | "PARTIAL";
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            stats?: {
                jobs_found?: number;
                jobs_new?: number;
                jobs_scored?: number;
                connectors_failed?: string[];
            };
        };
        Dashboard: {
            jobs_found?: number;
            jobs_applied?: number;
            interviews?: number;
            rejections?: number;
            offers?: number;
            success_rate?: number;
            recruiter_response_rate?: number;
            applications_by_week?: {
                week?: string;
                count?: number;
            }[];
            applications_by_company?: {
                company?: string;
                count?: number;
            }[];
            match_score_distribution?: {
                bucket?: string;
                count?: number;
            }[];
            salary_distribution?: {
                bucket?: string;
                count?: number;
            }[];
            funnel?: {
                status?: components["schemas"]["ApplicationStatus"];
                count?: number;
            }[];
            ai_suggestions?: string[];
            top_matches?: components["schemas"]["Match"][];
        };
        Trends: {
            postings_per_day?: {
                /** Format: date */
                date?: string;
                count?: number;
            }[];
            booming_companies?: {
                company?: string;
                recent?: number;
                previous?: number;
                growth_pct?: number;
            }[];
            tech_demand?: {
                skill?: string;
                count?: number;
                trend_pct?: number;
            }[];
        };
        AiSettings: {
            provider_chain?: ("OLLAMA" | "OPENROUTER" | "GEMINI" | "ANTHROPIC" | "OPENAI")[];
            daily_token_budget?: number;
            /** @description Write-only values; GET returns masked (sk-***) */
            keys?: {
                [key: string]: string;
            };
            ollama_base_url?: string;
        };
        Prompt: {
            id?: number;
            key?: string;
            version?: number;
            template?: string;
            variables_schema?: Record<string, never>;
            active?: boolean;
        };
        ConnectorSetting: {
            connector_id?: string;
            display_name?: string;
            /** @enum {string} */
            compliance_mode?: "OFFICIAL_API" | "PUBLIC_FEED" | "SEARCH_LINK" | "USER_AUTHORIZED_AUTOMATION";
            enabled?: boolean;
            rate_limit_per_min?: number;
            healthy?: boolean;
            /** Format: date-time */
            last_success_at?: string;
        };
        WatchlistEntry: {
            /** Format: uuid */
            id?: string;
            company_name?: string;
            connector_id?: string;
            /** @description Connector-specific, e.g. ATS slug */
            config?: Record<string, never>;
            enabled?: boolean;
        };
        ScheduledTask: {
            key?: string;
            cron?: string;
            timezone?: string;
            enabled?: boolean;
            description?: string;
        };
        ScheduledRun: {
            id?: number;
            task_key?: string;
            /** @enum {string} */
            status?: "RUNNING" | "SUCCESS" | "FAILED" | "PARTIAL";
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            stats?: Record<string, never>;
            error?: string;
        };
        AuditEvent: {
            id?: number;
            /** Format: uuid */
            user_id?: string;
            /** @enum {string} */
            actor?: "USER" | "SYSTEM" | "ASSISTANT";
            event_type?: string;
            entity_type?: string;
            entity_id?: string;
            detail?: Record<string, never>;
            /** Format: date-time */
            created_at?: string;
        };
        JobPage: {
            items?: components["schemas"]["Job"][];
            page?: number;
            size?: number;
            total?: number;
        };
        MatchPage: {
            items?: components["schemas"]["Match"][];
            page?: number;
            size?: number;
            total?: number;
        };
        ApplicationPage: {
            items?: components["schemas"]["Application"][];
            page?: number;
            size?: number;
            total?: number;
        };
    };
    responses: {
        /** @description RFC-7807 problem */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        page: number;
        size: number;
        jobId: string;
        resumeId: string;
        applicationId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    full_name: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            409: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Rotated pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    refresh_token?: string;
                };
            };
        };
        responses: {
            /** @description Logged out; refresh token revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Reset email queued (always 202 to avoid enumeration) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    token: string;
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Password changed; all sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
        };
    };
    oauthAuthorize: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "google" | "github";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to provider consent screen */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauthCallback: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path: {
                provider: "google" | "github";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    full_name?: string;
                    timezone?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    getPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
        };
    };
    putPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Preferences"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
        };
    };
    getSkills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSkill"][];
                };
            };
        };
    };
    putSkills: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSkill"][];
            };
        };
        responses: {
            /** @description Replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getNotificationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationSettings"];
                };
            };
        };
    };
    putNotificationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationSettings"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listResumes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"][];
                };
            };
        };
    };
    uploadResume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    name: string;
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Parsed + stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resumeId: components["parameters"]["resumeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resume"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    deleteResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resumeId: components["parameters"]["resumeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resumeId: components["parameters"]["resumeId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                    structured?: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setDefaultResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resumeId: components["parameters"]["resumeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Now the default */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    analyzeResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resumeId: components["parameters"]["resumeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI analysis (ATS score, strengths, gaps, suggestions) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeAnalysis"];
                };
            };
        };
    };
    downloadResume: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resumeId: components["parameters"]["resumeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                /** @description Title keyword search */
                q?: string;
                employment?: components["schemas"]["EmploymentType"];
                arrangement?: components["schemas"]["ContractArrangement"];
                workplace?: components["schemas"]["WorkplaceType"];
                country?: string;
                city?: string;
                sponsorship?: components["schemas"]["SponsorshipFlag"];
                min_salary?: number;
                posted_within_hours?: number;
                connector_id?: string;
                /** @description Filter by my match score */
                min_score?: number;
                sort?: "posted_at" | "-posted_at" | "score" | "-score";
                page?: components["parameters"]["page"];
                size?: components["parameters"]["size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["jobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job + extraction + my score */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    exportJobs: {
        parameters: {
            query?: {
                min_score?: number;
                posted_within_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSV */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                };
            };
        };
    };
    listSearchRuns: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                size?: components["parameters"]["size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["SearchRun"][];
                        page?: number;
                        size?: number;
                        total?: number;
                    };
                };
            };
        };
    };
    triggerSearchRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchRun"];
                };
            };
            /** @description A run is already in progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getSearchRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchRun"];
                };
            };
        };
    };
    listMatches: {
        parameters: {
            query?: {
                min_score?: number;
                since?: string;
                resume_id?: string;
                page?: components["parameters"]["page"];
                size?: components["parameters"]["size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked matches */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPage"];
                };
            };
        };
    };
    getMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["jobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full score breakdown + reasoning */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchScore"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    recomputeMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["jobId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    resume_id?: string;
                };
            };
        };
        responses: {
            /** @description Recompute queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listApplications: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApplicationStatus"];
                q?: string;
                page?: components["parameters"]["page"];
                size?: components["parameters"]["size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPage"];
                };
            };
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    job_id: string;
                    status?: components["schemas"]["ApplicationStatus"];
                    notes?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description Already tracked */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["applicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
        };
    };
    deleteApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["applicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["applicationId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    notes?: string;
                    salary_offered?: number;
                    /** Format: date-time */
                    deadline_at?: string;
                    /** Format: date-time */
                    next_action_at?: string;
                    /** Format: uuid */
                    resume_id?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    changeApplicationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["applicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    to_status: components["schemas"]["ApplicationStatus"];
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Status changed; event recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listApplicationEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["applicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationEvent"][];
                };
            };
        };
    };
    addApplicationContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["applicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationContact"];
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    autoApply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["applicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Apply task queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Automation not permitted for this source */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                job_id?: string;
                doc_type?: components["schemas"]["DocumentType"];
                page?: components["parameters"]["page"];
                size?: components["parameters"]["size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["GeneratedDocument"][];
                        page?: number;
                        size?: number;
                        total?: number;
                    };
                };
            };
        };
    };
    generateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    job_id: string;
                    doc_type: components["schemas"]["DocumentType"];
                    /**
                     * Format: uuid
                     * @description Defaults to the default resume
                     */
                    resume_id?: string;
                };
            };
        };
        responses: {
            /** @description Generation queued; poll the returned document id */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK (status + content when ready) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedDocument"];
                };
            };
        };
    };
    downloadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rendered docx/pdf */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    listConversations: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                size?: components["parameters"]["size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["Conversation"][];
                        page?: number;
                        size?: number;
                        total?: number;
                    };
                };
            };
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    title?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation with messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
        };
    };
    deleteConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    content: string;
                };
            };
        };
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    getTrends: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hiring trends + tech demand over time */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trends"];
                };
            };
        };
    };
    getAiSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider chain + budgets (keys masked) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSettings"];
                };
            };
        };
    };
    putAiSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiSettings"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listPrompts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prompt"][];
                };
            };
        };
    };
    createPromptVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Prompt"];
            };
        };
        responses: {
            /** @description New version created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    activatePrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                promptId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This version is now active for its key */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorSetting"][];
                };
            };
        };
    };
    updateConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connectorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled?: boolean;
                    rate_limit_per_min?: number;
                    config?: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWatchlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistEntry"][];
                };
            };
        };
    };
    addWatchlistEntry: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistEntry"];
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSchedules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduledTask"][];
                };
            };
        };
    };
    updateSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    cron?: string;
                    enabled?: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    runScheduleNow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taskKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Triggered */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRuns: {
        parameters: {
            query?: {
                task_key?: string;
                page?: components["parameters"]["page"];
                size?: components["parameters"]["size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scheduler run history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["ScheduledRun"][];
                        page?: number;
                        size?: number;
                        total?: number;
                    };
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                size?: components["parameters"]["size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["User"][];
                        page?: number;
                        size?: number;
                        total?: number;
                    };
                };
            };
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                user_id?: string;
                event_type?: string;
                page?: components["parameters"]["page"];
                size?: components["parameters"]["size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["AuditEvent"][];
                        page?: number;
                        size?: number;
                        total?: number;
                    };
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liveness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DB + Redis reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A dependency is down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
